version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./siawase_token:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "cd siawase-portal && npm start"
    ports:
      - "3001:3001"
    stdin_open: true
    